const AreaCodes = [
    { key: 'al', value: '+355', flag: 'al', text: 'Albania (+355)' },
    { key: 'ad', value: '+376', flag: 'ad', text: 'Andorra (+376)' },
    { key: 'ar', value: '+54', flag: 'ar', text: 'Argentina (+54)' },
    { key: 'au', value: '+61', flag: 'au', text: 'Australia (+61)' },
    { key: 'at', value: '+43', flag: 'at', text: 'Austria (+43)' },
    { key: 'by', value: '+375', flag: 'by', text: 'Belarus (+375)' },
    { key: 'be', value: '+32', flag: 'be', text: 'Belgium (+32)' },
    { ket: 'ba', value: '+387', flag: 'ba', text: 'Bosnia (+387)' },
    { key: 'bg', value: '+359', flag: 'bg', text: 'Bulgaria (+359)' },
    { key: 'ca', value: '+1', flag: 'ca', text: 'Canada (+1)' },
    { key: 'cn', value: '+86', flag: 'cn', text: 'China (+86)' },
    { key: 'hr', value: '+385', flag: 'hr', text: 'Croatia (+385)' },
    { key: 'cy', value: '+957', flag: 'cy', text: 'Cyprus (+957)' },
    { key: 'cz', value: '+420', flag: 'cz', text: 'Czech Republic (+420)' },
    { key: 'dk', value: '+45', flag: 'dk', text: 'Denmark (+45)' },
    { key: 'gb', value: '+44', flag: 'gb', text: 'England (+44)' },
    { key: 'fi', value: '+358', flag: 'fi', text: 'Finland (+358)' },
    { key: 'fr', value: '+33', flag: 'fr', text: 'France (+33)' },
    { key: 'de', value: '+49', flag: 'de', text: 'Germany (+49)' },
    { key: 'gr', value: '+30', flag: 'gr', text: 'Greece (+30)' },
    { key: 'hu', value: '+36', flag: 'hu', text: 'Hungary (+36)' },
    { key: 'il', value: '+972', flag: 'il', text: 'Israel (+972)' },
    { key: 'it', value: '+39', flag: 'it', text: 'Italy (+39)' },
    { key: 'jp', value: '+81', flag: 'jp', text: 'Japan (+81)' },
    { key: 'lv', value: '+371', flag: 'lv', text: 'Latvia (+371)' },
    { key: 'li', value: '+423', flag: 'li', text: 'Liechtenstein (+423)' },
    { key: 'lt', value: '+370', flag: 'lt', text: 'Lithuania (+370)' },
    { key: 'lu', value: '+352', flag: 'lu', text: 'Luxembourg (+352)' },
    { key: 'mk', value: '+389', flag: 'mk', text: 'Macedonia (+389)' },
    { key: 'me', value: '+382', flag: 'me', text: 'Montenegro (+382)' },
    { key: 'nl', value: '+31', flag: 'nl', text: 'Netherlands (+31)' },
    { key: 'nz', value: '+64', flag: 'nz', text: 'New Zealand (+64)' },
    { key: 'no', value: '+47', flag: 'no', text: 'Norway (+47)' },
    { key: 'pl', value: '+48', flag: 'pl', text: 'Poland (+48)' },
    { key: 'pt', value: '+351', flag: 'pt', text: 'Portugal (+351)' },
    { key: 'ro', value: '+40', flag: 'ro', text: 'Romania (+40)' },
    { key: 'ru', value: '+7', flag: 'ru', text: 'Russia (+7)' },
    { key: 'rs', value: '+381', flag: 'rs', text: 'Serbia (+381)' },
    { key: 'sk', value: '+421', flag: 'sk', text: 'Slovakia (+421)' },
    { key: 'si', value: '+386', flag: 'si', text: 'Slovenia (+386)' },
    { key: 'es', value: '+34', flag: 'es', text: 'Spain (+34)' },
    { key: 'se', value: '+46', flag: 'se', text: 'Sweden (+46)' },
    { key: 'ch', value: '+41', flag: 'ch', text: 'Switzerland (+41)' },
    { key: 'tr', value: '+1 649', flag: 'tr', text: 'Turkey (+1 649)' },
    { key: 'ua', value: '+380', flag: 'ua', text: 'Ukraine (+380)' },
    { key: 'us', value: '+1', flag: 'us', text: 'United States (+1)' },
    { key: 've', value: '+58', flag: 've', text: 'Venezuela (+58)' },
];

export default AreaCodes;