const States = [
    { key: 'al', value: 'Albania', flag: 'al', text: 'Albania' },
    { key: 'ad', value: 'Andorra', flag: 'ad', text: 'Andorra' },
    { key: 'ar', value: 'Argentina', flag: 'ar', text: 'Argentina' },
    { key: 'au', value: 'Australia', flag: 'au', text: 'Australia' },
    { key: 'at', value: 'Austria', flag: 'at', text: 'Austria' },
    { key: 'by', value: 'Belarus', flag: 'by', text: 'Belarus' },
    { key: 'be', value: 'Belgium', flag: 'be', text: 'Belgium' },
    { ket: 'ba', value: 'Bosnia', flag: 'ba', text: 'Bosnia' },
    { key: 'bg', value: 'Bulgaria', flag: 'bg', text: 'Bulgaria' },
    { key: 'ca', value: 'Canada', flag: 'ca', text: 'Canada' },
    { key: 'cn', value: 'China', flag: 'cn', text: 'China' },
    { key: 'hr', value: 'Croatia', flag: 'hr', text: 'Croatia' },
    { key: 'cy', value: 'Cyprus', flag: 'cy', text: 'Cyprus' },
    { key: 'cz', value: 'Czech Republic', flag: 'cz', text: 'Czech Republic' },
    { key: 'dk', value: 'Denmark', flag: 'dk', text: 'Denmark' },
    { key: 'gb', value: 'England', flag: 'gb', text: 'England' },
    { key: 'fi', value: 'Finland', flag: 'fi', text: 'Finland' },
    { key: 'fr', value: 'France', flag: 'fr', text: 'France' },
    { key: 'de', value: 'Germany', flag: 'de', text: 'Germany' },
    { key: 'gr', value: 'Greece', flag: 'gr', text: 'Greece' },
    { key: 'hu', value: 'Hungary', flag: 'hu', text: 'Hungary' },
    { key: 'il', value: 'Israel', flag: 'il', text: 'Israel' },
    { key: 'it', value: 'Italy', flag: 'it', text: 'Italy' },
    { key: 'jp', value: 'Japan', flag: 'jp', text: 'Japan' },
    { key: 'lv', value: 'Latvia', flag: 'lv', text: 'Latvia' },
    { key: 'li', value: 'Liechtenstein', flag: 'li', text: 'Liechtenstein' },
    { key: 'lt', value: 'Lithuania', flag: 'lt', text: 'Lithuania' },
    { key: 'lu', value: 'Luxembourg', flag: 'lu', text: 'Luxembourg' },
    { key: 'mk', value: 'Macedonia', flag: 'mk', text: 'Macedonia' },
    { key: 'me', value: 'Montenegro', flag: 'me', text: 'Montenegro' },
    { key: 'nl', value: 'Netherlands', flag: 'nl', text: 'Netherlands' },
    { key: 'nz', value: 'New Zealand', flag: 'nz', text: 'New Zealand' },
    { key: 'no', value: 'Norway', flag: 'no', text: 'Norway' },
    { key: 'pl', value: 'Poland', flag: 'pl', text: 'Poland' },
    { key: 'pt', value: 'Portugal', flag: 'pt', text: 'Portugal' },
    { key: 'ro', value: 'Romania', flag: 'ro', text: 'Romania' },
    { key: 'ru', value: 'Russia', flag: 'ru', text: 'Russia' },
    { key: 'rs', value: 'Serbia', flag: 'rs', text: 'Serbia' },
    { key: 'sk', value: 'Slovakia', flag: 'sk', text: 'Slovakia' },
    { key: 'si', value: 'Slovenia', flag: 'si', text: 'Slovenia' },
    { key: 'es', value: 'Spain', flag: 'es', text: 'Spain' },
    { key: 'se', value: 'Sweden', flag: 'se', text: 'Sweden' },
    { key: 'ch', value: 'Switzerland', flag: 'ch', text: 'Switzerland' },
    { key: 'tr', value: 'Turkey', flag: 'tr', text: 'Turkey' },
    { key: 'ua', value: 'Ukraine', flag: 'ua', text: 'Ukraine' },
    { key: 'us', value: 'United States', flag: 'us', text: 'United States' },
    { key: 've', value: 'Venezuela', flag: 've', text: 'Venezuela' },
];

export default States;